# Generated by Django 4.2.6 on 2023-10-12 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerID', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=150)),
                ('suburb', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=3)),
                ('postcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.CharField(max_length=7)),
                ('orderDate', models.DateField()),
                ('shipped', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1)),
                ('shippingDate', models.DateField(blank=True, null=True)),
                ('staffID', models.IntegerField()),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pracTest.customer')),
            ],
        ),
    ]
